def generate_report(

    account_id,

    risk_score,

    explanation,

    notes

):

    report = f"""

SOCMINT INVESTIGATION REPORT

=================================

Account ID:
{account_id}

Risk Score:
{risk_score}

Explanation:
{explanation}

Investigator Notes:
{notes}

=================================

Generated by:
SOCMINT Suspect Profiling System

"""

    return report


def save_report(

    account_id,

    report

):

    filename = (
        f"reports/{account_id}.txt"
    )

    with open(

        filename,

        "w",

        encoding="utf-8"

    ) as file:

        file.write(
            report
        )

    return filename
